In [1]:
%pwd

'/home/phil/Coding/thesis-code/arco/notebooks'

In [2]:
%cd ./..

/home/phil/Coding/thesis-code/arco

In [3]:
# Load OPENAI API KEY from the keychain
import os, subprocess
os.environ["OPENAI_API_KEY"] = subprocess.check_output(["secret-tool", "lookup", "app", "thesis", "provider", "openai"], text=True)

In [25]:
from arco.cli.commands import bench
from pathlib import Path
import pandas as pd

dataset = "./data/benchmarks/benchmark_dataset.json"
low_temp_config = "./config/notebook_configs/low_temp_bench.yaml"
high_temp_config = "./config/notebook_configs/high_temp_bench.yaml"

for path in [dataset, low_temp_config, high_temp_config]:
    assert Path(path).is_file(), f"Missing file: {path}"

In [5]:
def load_or_execute(name : str) -> pd.DataFrame:
    if Path(f"output/benchmarks/{name}.csv").is_file():
        print("Loaded from previous execution")
        return pd.read_csv(f"output/benchmarks/{name}.csv")
    return bench.run_benchmark(dataset, config_path=f"./config/notebook_configs/{name}.yaml", benchmark_id=name)

In [6]:
# Low temp run
low_temp_df = load_or_execute("low_temp_bench")

Loaded from previous execution

In [7]:
low_temp_df[["Retriever_1_evaluation_gt","Retriever_1_perplexity",
             "Analyzer_1_evaluation_gt", "Analyzer_1_perplexity",
             "Visualizer_1_evaluation_gt", "Visualizer_1_perplexity"]]

,Retriever_1_evaluation_gt,Retriever_1_perplexity,Analyzer_1_evaluation_gt,Analyzer_1_perplexity,Visualizer_1_evaluation_gt,Visualizer_1_perplexity
0,1.0,1.021673,1.000,1.144366,1.00,1.005095
1,1.0,1.005706,1.000,1.025209,1.00,1.004617
2,1.0,1.025137,1.000,1.063267,NaN,NaN
3,1.0,1.003387,1.000,1.043302,0.90,1.028141
4,1.0,1.006178,1.000,1.101254,1.00,1.002141
5,1.0,1.029462,1.000,1.111152,1.00,1.034476
6,1.0,1.006221,1.000,1.027701,NaN,NaN
7,1.0,1.019610,1.000,1.019244,0.95,1.029544
8,1.0,1.027443,1.000,1.017620,NaN,NaN
9,1.0,1.004679,1.000,1.098894,0.90,1.013532
10,1.0,1.035063,1.000,1.023756,1.00,1.004498
11,1.0,1.011190,1.000,1.138788,1.00,1.006409
12,1.0,1.002637,1.000,1.045826,1.00,1.051199
13,1.0,1.005913,1.000,1.053475,1.00,1.030415
14,1.0,1.015861,1.000,1.017554,NaN,NaN
15,1.0,1.005496,1.000,1.018984,NaN,NaN
16,1.0,1.010869,1.000,1.143909,1.00,1.003927
17,1.0,1.003360,1.000,1.057252,1.00,1.002391
18,1.0,1.016396,1.000,1.045526,0.90,NaN
19,1.0,1.032335,0.875,1.010872,NaN,NaN

In [8]:
# High temp run
high_temp_df = load_or_execute("high_temp_bench")

Loaded from previous execution

In [9]:
high_temp_df[["Retriever_1_evaluation_gt","Retriever_1_perplexity",
             "Analyzer_1_evaluation_gt", "Analyzer_1_perplexity",
             "Visualizer_1_evaluation_gt", "Visualizer_1_perplexity"]]

,Retriever_1_evaluation_gt,Retriever_1_perplexity,Analyzer_1_evaluation_gt,Analyzer_1_perplexity,Visualizer_1_evaluation_gt,Visualizer_1_perplexity
0,1.0,1.032490,1.000,1.857559e+00,1.00,1.008088
1,1.0,1.006492,1.000,1.255682e+41,1.00,1.007618
2,1.0,1.021042,1.000,1.265129e+00,NaN,NaN
3,1.0,1.002796,1.000,1.155036e+00,0.95,1.046467
4,1.0,1.006588,0.750,1.193014e+00,1.00,1.001909
5,1.0,1.029613,1.000,1.179915e+00,1.00,1.033257
6,1.0,1.004943,1.000,5.086212e+32,NaN,NaN
7,1.0,1.018259,1.000,1.132432e+00,1.00,1.027226
8,1.0,1.022871,1.000,1.457784e+00,NaN,NaN
9,1.0,1.005793,1.000,1.201226e+00,0.90,1.044378
10,1.0,1.022194,1.000,1.036793e+00,1.00,1.005270
11,1.0,1.014339,1.000,1.336540e+00,1.00,1.006309
12,1.0,1.003107,1.000,1.171886e+00,1.00,1.040908
13,1.0,1.005936,1.000,1.057286e+00,0.90,1.011788
14,1.0,1.016089,0.875,1.075644e+00,NaN,NaN
15,1.0,1.005178,1.000,1.044745e+00,NaN,NaN
16,1.0,1.008202,1.000,2.107697e+34,1.00,1.005453
17,1.0,1.004791,1.000,1.212351e+00,1.00,1.001937
18,1.0,1.026803,0.750,1.367426e+00,0.90,1.017909
19,1.0,1.032870,1.000,1.066270e+00,NaN,NaN

In [22]:
from arco.cli.commands.bench import load_benchmark_dataset
bench_dataset = load_benchmark_dataset(dataset)
def show_diff(gt_df, benchmark_df, idx):
    prompt = gt_df[idx]["prompt"]
    analysis = benchmark_df["Analyzer_1_message"].loc[idx]
    gt_analysis = gt_df[idx]["gt_analysis"]
    perplexity = benchmark_df["Analyzer_1_perplexity"].loc[idx]
    accuracy = benchmark_df["Analyzer_1_evaluation_gt"].loc[idx]
    print(f"""
    Prompt: {prompt}
    Analysis: {analysis}
    GT Analysis: {gt_analysis}
    Perplexity: {perplexity}
    Accuracy: {accuracy}
    """)

In [23]:
show_diff(bench_dataset, low_temp_df, 1)

    Prompt: Show the 12 months of 2023 with total revenue and total units sold
    Analysis: In 2023, the total revenue and total units sold for each month are as follows: January - $434,172.81 with 33,653 units; February - $411,762.72 with 31,545 units; March - $423,070.84 with 32,460 units; April - $384,479.68 with 30,199 units; May - $381,326.43 with 31,154 units; June - $364,806.74 with 29,082 units; July - $353,284.21 with 27,932 units; August - $401,061.54 with 31,903 units; September - $422,554.97 with 31,847 units; October - $454,231.06 with 38,208 units; November - $511,104.29 with 41,043 units; December - $874,263.67 with 60,941 units. The total revenue for the year is $5,416,118.96, with a total of 419,967 units sold.
    GT Analysis: The 12 months of 2023 show total revenue ranging from $353,284.21 (July) to $874,263.67 (December), with total units from 27,932 to 60,941.
    Perplexity: 1.0252090942581082
    Accuracy: 1.0

In [24]:
show_diff(bench_dataset, high_temp_df, 1)

    Prompt: Show the 12 months of 2023 with total revenue and total units sold
    Analysis: In 2023, the total revenue and total units sold are as follows: January had $434,172.81 in total revenue with 33,653 units sold; February reported $411,762.72 in revenue and 31,545 units sold; March generated $423,070.84 with 32,460 units sold; April netted $384,479.68 and 30,199 units; May achieved $381,326.43 with 31,154 units; June reached $364,806.74 and 29,082 units; July recorded $353,284.21 with 27,932 units sold; August earned $401,061.54 and sold 31,903 units; September saw $422,554.97 in revenue with 31,847 units sold; October produced $454,231.06 with 38,208 units sold; November garnered $511,104.29 and 41,043 units; December generated $874,263.67 with 60,941 units sold.
    GT Analysis: The 12 months of 2023 show total revenue ranging from $353,284.21 (July) to $874,263.67 (December), with total units from 27,932 to 60,941.
    Perplexity: 1.255681572840076e+41
    Accuracy: 1.0

In [43]:
import pandas as pd
from scipy.stats import pearsonr

def compute_result_correlation(df):
    columns = ["Retriever_1", "Analyzer_1", "Visualizer_1"]
    results = {}

    all_gt = []
    all_perplexity = []

    for column in columns:
        gt = df[f"{column}_evaluation_gt"]
        perp = df[f"{column}_perplexity"]

        # Remove missing values
        valid = pd.concat([gt, perp], axis=1).dropna()
        gt = valid.iloc[:, 0]
        perp = valid.iloc[:, 1]

        if len(gt) < 2 or gt.nunique() <= 1 or perp.nunique() <= 1:
            if len(gt) < 2 : print(f"len(gt)={len(gt)}")
            if gt.nunique() <=1 : print(f"gt.nunique() = {gt.nunique()}")
            if perp.nunique() <=1 : print(f"perp.nunique() = {perp.nunique()}")
            corr, p_value = float("nan"), float("nan")
        else:
            corr, p_value = pearsonr(gt, perp)

        results[column] = {"correlation": corr, "p_value": p_value}

        all_gt.extend(gt)
        all_perplexity.extend(perp)

    all_gt = pd.Series(all_gt)
    all_perplexity = pd.Series(all_perplexity)

    if all_gt.nunique() <= 1 or all_perplexity.nunique() <= 1:
        overall_corr, overall_p = float("nan"), float("nan")
    else:
        overall_corr, overall_p = pearsonr(all_gt, all_perplexity)

    print("Per-column correlations:")
    for col, res in results.items():
        print(
            f"  {col}: r = {res['correlation']:.4f}, "
            f"p = {res['p_value']:.4f}"
        )

    print(f"\nOverall: r = {overall_corr:.4f}, p = {overall_p:.4f}")

    return results, (overall_corr, overall_p)

In [44]:
corr_low, overall_corr_low = compute_result_correlation(low_temp_df)

gt.nunique() = 1
Per-column correlations:
  Retriever_1: r = nan, p = nan
  Analyzer_1: r = 0.2545, p = 0.2789
  Visualizer_1: r = -0.1998, p = 0.5129

Overall: r = 0.1023, p = 0.4661

In [45]:
corr_high, overall_corr_high = compute_result_correlation(high_temp_df)

gt.nunique() = 1
Per-column correlations:
  Retriever_1: r = nan, p = nan
  Analyzer_1: r = 0.0921, p = 0.6992
  Visualizer_1: r = -0.3552, p = 0.2126

Overall: r = 0.0462, p = 0.7400